<a href="https://colab.research.google.com/github/Lawal-Abdulsabur/Access-to-affordable-drinking-water-project-1/blob/main/Day_3__Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files

In [ ]:
import pandas as pd

In [ ]:
uploaded = files.upload()

Saving pharmacy 2_messy.csv to pharmacy 2_messy.csv

In [11]:
df = pd.read_csv("pharmacy 2_messy.csv")
print("dataloaded")

dataloaded

In [12]:
df.shape

(200, 12)

In [13]:
df.columns

Index(['Receipt ID', 'BRANCH', 'Customer Type', 'Gender', 'Drug Category',
       'Unit Price', 'Quantity', 'Total Amount', 'Date', 'Payment Method',
       'Pharmacist Name', 'Rating'],
      dtype='object')

In [14]:
df.columns = df.columns.str.lower().str.strip().str.replace(" "," _ ")
print("Cleaned columns:")
for col in df.columns:
 print(repr(col))

Cleaned columns:
'receipt _ id'
'branch'
'customer _ type'
'gender'
'drug _ category'
'unit _ price'
'quantity'
'total _ amount'
'date'
'payment _ method'
'pharmacist _ name'
'rating'

In [15]:
print("Final columns name")
print(df.columns.tolist())

Final columns name
['receipt _ id', 'branch', 'customer _ type', 'gender', 'drug _ category', 'unit _ price', 'quantity', 'total _ amount', 'date', 'payment _ method', 'pharmacist _ name', 'rating']

In [16]:
df.head()

,receipt _ id,branch,customer _ type,gender,drug _ category,unit _ price,quantity,total _ amount,date,payment _ method,pharmacist _ name,rating
0,RX-9824-191,Kumasi,Prescription,Male,Skincare,GHS 39.87,4,159.48,4/17/2023,Mobile Money,Ama Mensah,4.8
1,RX-3494-572,Takoradi,Prescription,Male,Antimalarials,GHS 145.83,10,1458.30,"June 7, 2023",Mobile Money,NaN,8.8
2,RX-1124-535,Takoradi,Walk-in,Female,Antibiotics,GHS 189.64,9,1706.76,"January 9, 2023",Cash,Yaw Darko,5.2
3,RX-3634-865,Accra Central,Prescription,Male,Antimalarials,GHS 106.14,4,424.56,2/23/2023,Card,Ama Mensah,5.5
4,RX-7865-183,Kumasi,Insurance,Male,Skincare,GHS 133.76,1,133.76,6/27/2023,Cash,NaN,4.2

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   receipt _ id       200 non-null    object
 1   branch             200 non-null    object
 2   customer _ type    200 non-null    object
 3   gender             200 non-null    object
 4   drug _ category    200 non-null    object
 5   unit _ price       200 non-null    object
 6   quantity           200 non-null    int64
 7   total _ amount     188 non-null    float64
 8   date               200 non-null    object
 9   payment _ method   200 non-null    object
 10  pharmacist _ name  190 non-null    object
 11  rating             185 non-null    float64
dtypes: float64(2), int64(1), object(9)
memory usage: 18.9+ KB

In [18]:
df.describe()

         quantity  total _ amount      rating
count  200.000000      188.000000  185.000000
mean     6.210000      609.114840    6.342703
std      3.499591      527.845615    2.143662
min      1.000000       15.060000    3.000000
25%      3.000000      182.705000    4.400000
50%      6.000000      406.480000    6.500000
75%      9.000000      930.980000    8.300000
max     12.000000     2287.680000    9.800000

1. unit_price needs to be changed to numeric

2. date needs to be chaged to datatime

3. quantity needs to be a numeric variable

4. sevaral columns have missing values

In [21]:
# Before
print("Type before:" , df["unit _ price"].dtype)

print(df["unit _ price"])

Type before: object
0       GHS 39.87
1      GHS 145.83
2      GHS 189.64
3      GHS 106.14
4      GHS 133.76
          ...
195    GHS 116.61
196    GHS 118.71
197     GHS 41.21
198    GHS 102.24
199     GHS 28.01
Name: unit _ price, Length: 200, dtype: object

In [24]:
 # Step- 1 remove the GHS
df["unit _ price"]= df["unit _ price"].str.replace("GHS" , "").str.strip()
# Step-2 Convert to number
df["unit _ price"] = pd.to_numeric(df["unit _ price"], errors="coerce")
print("Type after", df["unit _ price"].dtype)
print(df["unit _ price"].head(3))

Type after float64
0     39.87
1    145.83
2    189.64
Name: unit _ price, dtype: float64

In [25]:
# Before
print("Type before", df["quantity"].dtype)
print(df["quantity"].head(3))

Type before int64
0     4
1    10
2     9
Name: quantity, dtype: int64

In [26]:
# Before
print("Type before:", df["date"].dtype)
print(df["date"].head(6))

Type before: object
0          4/17/2023
1       June 7, 2023
2    January 9, 2023
3          2/23/2023
4          6/27/2023
5      April 7, 2023
Name: date, dtype: object

In [29]:
df["date"] =  pd.to_datetime(df["date"], format = "mixed")

# After
print("Type after:" , df["date"].dtype)
print(df["date"].head(6))

Type after: datetime64[ns]
0   2023-04-17
1   2023-06-07
2   2023-01-09
3   2023-02-23
4   2023-06-27
5   2023-04-07
Name: date, dtype: datetime64[ns]

In [30]:
# Extract months and days from the date
df["month"]= df["date"].dt.month
df["day"] = df["date"].dt.day
print(df[["date",
          "month" , "day"]].head())

        date  month  day
0 2023-04-17      4   17
1 2023-06-07      6    7
2 2023-01-09      1    9
3 2023-02-23      2   23
4 2023-06-27      6   27

In [31]:
df.dtypes

receipt _ id                 object
branch                       object
customer _ type              object
gender                       object
drug _ category              object
unit _ price                float64
quantity                      int64
total _ amount              float64
date                 datetime64[ns]
payment _ method             object
pharmacist _ name            object
rating                      float64
month                         int32
day                           int32
dtype: object

In [32]:
# Count missing values
print(df.isnull().sum())

receipt _ id          0
branch                0
customer _ type       0
gender                0
drug _ category       0
unit _ price          0
quantity              0
total _ amount       12
date                  0
payment _ method      0
pharmacist _ name    10
rating               15
month                 0
day                   0
dtype: int64

In [33]:
missing_pct = (df.isnull().sum()/len(df)*100).round(1)
print(missing_pct)

receipt _ id         0.0
branch               0.0
customer _ type      0.0
gender               0.0
drug _ category      0.0
unit _ price         0.0
quantity             0.0
total _ amount       6.0
date                 0.0
payment _ method     0.0
pharmacist _ name    5.0
rating               7.5
month                0.0
day                  0.0
dtype: float64

In [35]:
# filling missing numbers with the column average
df["total _ amount"]= df["total _ amount"].fillna(df["total _ amount"].mean())
df["rating"]= df["rating"].fillna(df["rating"].mean())
print("missing in rating:",df["rating"].isnull().sum())
print("missing in total:" , df["total _ amount"].isnull().sum())

missing in rating: 0
missing in total: 0

In [36]:
df["pharmacist _ name"] = df["pharmacist _ name"].fillna("unknown")

In [37]:
# check how many rows still have missing values
print("Remaining missing values:")
print(df.isnull().sum())

Remaining missing values:
receipt _ id         0
branch               0
customer _ type      0
gender               0
drug _ category      0
unit _ price         0
quantity             0
total _ amount       0
date                 0
payment _ method     0
pharmacist _ name    0
rating               0
month                0
day                  0
dtype: int64

In [40]:
# Drop the remaining rows with misssing values
print("Row before dropping:", len(df))
df= df.dropna()
print("Rows after droping:" , len(df))

Row before dropping: 200
Rows after droping: 200

In [41]:
print("missing value remaining:" )
print(df.isnull().sum())
print("Final Shape:" , df.shape)

missing value remaining:
receipt _ id         0
branch               0
customer _ type      0
gender               0
drug _ category      0
unit _ price         0
quantity             0
total _ amount       0
date                 0
payment _ method     0
pharmacist _ name    0
rating               0
month                0
day                  0
dtype: int64
Final Shape: (200, 14)

In [42]:
df.head()

,receipt _ id,branch,customer _ type,gender,drug _ category,unit _ price,quantity,total _ amount,date,payment _ method,pharmacist _ name,rating,month,day
0,RX-9824-191,Kumasi,Prescription,Male,Skincare,39.87,4,159.48,2023-04-17,Mobile Money,Ama Mensah,4.8,4,17
1,RX-3494-572,Takoradi,Prescription,Male,Antimalarials,145.83,10,1458.30,2023-06-07,Mobile Money,unknown,8.8,6,7
2,RX-1124-535,Takoradi,Walk-in,Female,Antibiotics,189.64,9,1706.76,2023-01-09,Cash,Yaw Darko,5.2,1,9
3,RX-3634-865,Accra Central,Prescription,Male,Antimalarials,106.14,4,424.56,2023-02-23,Card,Ama Mensah,5.5,2,23
4,RX-7865-183,Kumasi,Insurance,Male,Skincare,133.76,1,133.76,2023-06-27,Cash,unknown,4.2,6,27

In [43]:
df.tail()

,receipt _ id,branch,customer _ type,gender,drug _ category,unit _ price,quantity,total _ amount,date,payment _ method,pharmacist _ name,rating,month,day
195,RX-1162-248,Takoradi,Prescription,Male,Skincare,116.61,6,699.66,2023-06-05,Insurance,Yaw Darko,3.8,6,5
196,RX-4300-561,Accra Central,Prescription,Male,Skincare,118.71,11,1305.81,2023-05-22,Insurance,Abena Owusu,5.5,5,22
197,RX-1907-743,Takoradi,Walk-in,Female,Vitamins & Supplements,41.21,2,82.42,2023-01-14,Mobile Money,Kofi Asante,9.0,1,14
198,RX-7313-719,Takoradi,Walk-in,Female,Antimalarials,102.24,2,204.48,2023-06-17,Mobile Money,Ama Mensah,7.9,6,17
199,RX-3248-830,Kumasi,Walk-in,Female,Painkillers,28.01,6,168.06,2023-04-06,Insurance,Abena Owusu,8.0,4,6